set(__QT_DEPLOY_TARGET_mx-snapshot_FILE /home/adrian/mx-snapshot/build-make/mx-snapshot)
set(__QT_DEPLOY_TARGET_mx-snapshot_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_helper_FILE /home/adrian/mx-snapshot/build-make/helper)
set(__QT_DEPLOY_TARGET_helper_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_iso-snapshot-cli_FILE /home/adrian/mx-snapshot/build-make/iso-snapshot-cli)
set(__QT_DEPLOY_TARGET_iso-snapshot-cli_TYPE EXECUTABLE)
