#!/bin/sh

set -e

case "$1" in
    configure)
      set +e
      if [ -n "$2" ] ; then
        echo "Looks like an upgrade, exiting postinst now ...."
        exit 0
      fi
      sudo cp /usr/share/mx-tweak/55-tweak-override.conf /etc/polkit-1/localauthority.conf.d/
      set -e
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
#! /bin/sh

set -e

#cleanup some old configs from bullseye/buster
if [ -e  /etc/polkit-1/localauthority.conf.d/55-tweak-override.conf ]; then
	rm /etc/polkit-1/localauthority.conf.d/55-tweak-override.conf
fi

if [ -e  /etc/polkit-1/localauthority/50-local.d/50-udisks.pkla ]; then
	rm /etc/polkit-1/localauthority/50-local.d/50-udisks.pkla
fi

if [ -e  /etc/tweak-udisks.chk ]; then
	rm /etc/tweak-udisks.chk
fi

exit 0
