#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then

	if [ ! -e "/usr/share/backgrounds/default23.png" ]; then
		cp /usr/share/backgrounds/THE_Dark_Metal.png /usr/share/backgrounds/default23.png
	fi

fi

#DEBHELPER#
