#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then

    # reset default25 to current default, remove alpha wallpaper
    if [ -e "/usr/share/backgrounds/remove_alpha" ]; then
    	rm /usr/share/backgrounds/default25.png
    	rm /usr/share/backgrounds/remove_alpha
    fi
	if [ ! -e "/usr/share/backgrounds/default25.png" ]; then
		cp /usr/share/backgrounds/Maturity.png /usr/share/backgrounds/default25.png
	fi

fi

#DEBHELPER#
