name: Build test Foliate Snap
on:
  push:
    branches:
      - gtk4
  workflow_dispatch:

jobs:
  snap:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Change Source
      run: yq 'del(.parts.foliate.source-tag) | .parts.foliate.source = "."' snapcraft.yaml
    - uses: canonical/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'release' }} #uploads the snap only if it's a release
      with:
        name: amber-snap
        path: ${{ steps.snapcraft.outputs.snap }}
