#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    if [ -n "$(grep linen /etc/plymouth/plymouthd.conf)" ]; then
		update-initramfs -u -k all
	fi    
fi

#DEBHELPER#
