#!/bin/bash

# Root level functions requiring password for mx-packageinstaller

cleanup_temp() {
    rm /etc/apt/sources.list.d/mxpitemp.list
}

copy_log() {
    echo -e "-----------------------------------------------------------\nMXPI SESSION\n-----------------------------------------------------------\n" >> /var/log/mxpi.log.old
    cat /var/log/mxpi.log >> /var/log/mxpi.log.old
    mv /tmp/mxpi.log /var/log
}

main() {
case "$1" in 
    copy_log) 
        copy_log;;
    cleanup_temp)
        cleanup_temp;;
esac
}

main "$@"
