.TH MAKE-CADIR "1" "November 2012" "1.0" "make-cadir man page"
.SH NAME
make-cadir \- create certificates dir
.SH SYNOPSIS
.B make-cadir
\fIDIR\fR
.SH DESCRIPTION
.PP
Creates a NEW directory, copying and linking any necessary files from the easy-rsa
package.
.PP
The specified DIR must not exist.
.SH AUTHOR
Written by Alberto Gonzalez Iniesta
.SH COPYRIGHT
Copyright \(co 2012 Alberto Gonzalez Iniesta
License GPLv2: GNU GPL version 2
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
