#!/bin/sh
case "$1" in
    install|upgrade)
      set +e
      echo "Diverting Calamares launcher ..."
      dpkg-divert --quiet --rename --divert /usr/bin/add-calamares-desktop-icon.real1 /usr/bin/add-calamares-desktop-icon
    ;;

    *)
    ;;
esac
#DEBHELPER#
